import type {NextPage} from 'next';
import Head from 'next/head';
import axios from 'axios';
import {useState, useEffect} from 'react';
import {useRouter} from 'next/router';

export interface Spell {
  _id: String;
  higher_level: string[];
  index: string;
  name: string;
  desc: string[];
  range: string;
  components: string[];
  material: string;
  ritual: boolean;
  duration: string;
  concentration: boolean;
  casting_time: string;
  level: number;
  dc: SpellDc;
  school: SpellMeta;
  classes: SpellMeta[];
  subclasses: SpellMeta[];
  url: string;
}

export interface SpellDc {
  dc_type: SpellMeta;
  dc_success: string;
}

export interface SpellMeta {
  index: string;
  name: string;
  url: string;
}

const Home: NextPage = () => {
  const [spellInfo, setSpellInfo] = useState<Spell>();
  const router = useRouter();
  const {spellid} = router.query;

  useEffect(() => {
    console.log(spellid);
    spellid &&
    axios.get(`https://www.dnd5eapi.co/api/spells/${spellid}`)
        .then((res) => setSpellInfo(res.data))
        .catch((err) => console.log(err));
  }, [spellid]);

  console.log(spellInfo);

  return (
    <div className='flex flex-col items-center min-h-screen'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='flex flex-col items-center justify-center md:w-[40rem] min-w-0 text-center'>
        <h1 className='text-emerald-700'>
          {/* <h1 className='text-emerald-700 text-2xl'> */}
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <div className='flex flex-row items-center justify-around mb-2 w-full'>
        </div>
        <p className='flex flex-row items-center justify-around mb-2 w-full'>
          Display single spell{' '}<br/>
          {spellInfo?.name}<br/>
          {spellInfo?.desc[0]}
        </p>
      </main>
    </div>
  );
};

export default Home;
