import type {NextPage} from 'next';
import Head from 'next/head';
import axios from 'axios';
import {useState, useEffect} from 'react';
// import Link from 'next/link';

export interface Spells {
  count: number;
  next: string;
  previous: string;
  results: SpellsResults[];
}

export interface SpellsResults {
  slug: string;
  name: string;
  desc?: string | null;
  higher_level: string;
  page: string;
  range: string;
  components: string;
  material: string;
  ritual: string;
  duration: string;
  concentration: string;
  casting_time: string;
  level: string;
  level_int: string;
  school: 'Evocation' | 'Conjuration' | 'Abjuration' | 'Transmutation' | 'Enchantment' | 'Necromancy' | 'Divination' | 'Illusion';
  dnd_class: string;
  archetype: string;
  circles: string;
}

const Home: NextPage = () => {
  const [spellList, setSpellList] = useState<SpellsResults[]>([]);
  const [filter, setFilter] = useState('');
  // const [spellInfo, setSpellInfo] = useState<SpellsResults>();

  // const getSpellList = () => {
  //   axios.get('https://www.dnd5eapi.co/api/spells')
  //     .then(res => setSpellList(res.data.results))
  //     .catch(err => console.log(err))
  // }

  const spellListBlock = (spells: SpellsResults[]) => {
    return spells.map(({slug, name}) =>
      <div key={slug} className='p-6 mt-4 mx-10 text-left border rounded-lg border-transparent bg-slate-200'>
        <li>
          <button className='mt-2 text-md text-blue-700' onClick= {
            () => null
          }>{name}</button>p
        </li>
      </div>
    );
  };

  useEffect(() => {
    axios.get('https://api.open5e.com/spells/')
        .then((res) => setSpellList(res.data.results))
        .catch((err) => console.log(err));
  }, []);

  const schoolSet = new Set<String>();
  spellList.forEach((spell) => schoolSet.add(spell.school));

  console.log(schoolSet);

  return (
    <div className='flex flex-col items-center min-h-screen'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='flex flex-col items-center justify-center md:w-[40rem] min-w-0 text-center'>
        <h1 className='text-emerald-700'>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>

        <p className='text-blue-600'>
          Full Spell List{' '}
        </p>
        <input type='text' id='spellSearch' name='spellSearch' value={filter} onChange = {
          (e) => {
            setFilter(e.target.value);
          }
        }/>
        {/*
        school: 'Evocation' | 'Conjuration' | 'Abjuration' | 'Transmutation' | 'Enchantment' | 'Necromancy' | 'Divination' | 'Illusion';
         */}
        <select name = 'schools' >
          {[...schoolSet].map((value, index) =>
            <option key={index}>{value}</option>
          )}
        </select>
        <div className='flex flex-row items-center justify-around mb-2 w-full'>
          <ul className='list-disc mx-10 mt-2 pl-6 text-xl font-bold'>
            {spellListBlock(spellList.filter((spell) => spell.school.match(filter)))}
            {/* {spellListBlock(spellList.filter(({school})) => school.match(filter))} */}
          </ul>
        </div>

        <p className='flex flex-row items-center justify-around mb-2 w-full'>
          Get single spell{' '}
        </p>
        <div className='flex flex-row items-center justify-around mb-2 w-full'>
          {/* <Link href={`/spelllist/spells/${spellInfo?.slug}`}>
            <a>
              {spellInfo?.name}
            </a>
          </Link> */}
        </div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
};

export default Home;
